# Preprocessing of Medical Data

##Patient Records

In [ ]:
import pandas as pd

The original "patients.csv" includes the personal information for 1162 clinical patients.

In [ ]:
patients=pd.read_csv("patients.csv")
patients

,Id,BIRTHDATE,DEATHDATE,SSN,DRIVERS,PASSPORT,PREFIX,FIRST,LAST,SUFFIX,...,BIRTHPLACE,ADDRESS,CITY,STATE,COUNTY,ZIP,LAT,LON,HEALTHCARE_EXPENSES,HEALTHCARE_COVERAGE
0,b9c610cd-28a6-4636-ccb6-c7a0d2a4cb85,2019-02-17,NaN,999-65-3251,NaN,NaN,NaN,Damon455,Langosh790,NaN,...,Middleborough Massachusetts US,620 Lynch Tunnel Apt 0,Springfield,Massachusetts,Hampden County,1104.0,42.080389,-72.480431,9.039165e+03,7964.1255
1,c1f1fcaa-82fd-d5b7-3544-c8f9708b06a8,2005-07-04,NaN,999-49-3323,S99941126,NaN,NaN,Thi53,Wunsch504,NaN,...,Danvers Massachusetts US,972 Tillman Branch Suite 48,Bellingham,Massachusetts,Norfolk County,NaN,42.035213,-71.482519,4.027234e+05,14064.1350
2,339144f8-50e1-633e-a013-f361391c4cff,1998-05-11,NaN,999-10-8743,S99996708,X75063318X,Mr.,Chi716,Greenfelder433,NaN,...,Athens Athens Prefecture GR,1060 Bernhard Crossroad Suite 15,Boston,Massachusetts,Suffolk County,2131.0,42.292557,-71.061160,5.719359e+05,787.5375
3,d488232e-bf14-4bed-08c0-a82f34b6a197,2003-01-28,NaN,999-56-6057,S99929424,NaN,Ms.,Phillis443,Walter473,NaN,...,Boston Massachusetts US,677 Ritchie Terrace,Hingham,Massachusetts,Plymouth County,2043.0,42.200491,-70.916076,5.825578e+05,104782.2070
4,217f95a3-4e10-bd5d-fb67-0cfb5e8ba075,1993-12-23,NaN,999-91-4320,S99991143,X44132498X,Mr.,Jerrold404,Herzog843,NaN,...,Boston Massachusetts US,276 Bernier Branch,Revere,Massachusetts,Suffolk County,NaN,42.381875,-70.999286,4.758269e+05,18067.0950
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1158,409330fa-7ffd-dbfb-4eba-2349d58a6324,1979-02-28,NaN,999-68-5445,S99991649,X72884711X,Mr.,Coy949,Schaden604,NaN,...,Fitchburg Massachusetts US,434 Hickle Throughway Suite 15,Amherst,Massachusetts,Hampshire County,NaN,42.380084,-72.527376,1.050937e+06,346.5075
1159,cb328021-a854-dc94-e7ae-426580477308,1964-05-31,NaN,999-10-6445,S99986790,X86596484X,Mrs.,Sherry479,Barrows492,NaN,...,Boston Massachusetts US,976 Ortiz Orchard,Stoughton,Massachusetts,Norfolk County,NaN,42.081223,-71.126028,8.031471e+05,553335.4420
1160,41862157-5c14-f706-4a94-d2929be969e7,1967-07-12,NaN,999-63-2407,S99976335,X68999803X,Mr.,Vance413,Jakubowski832,NaN,...,Brockton Massachusetts US,534 Strosin Corner,Gardner,Massachusetts,Worcester County,1440.0,42.604215,-72.013243,1.028321e+06,28607.5050
1161,d53c57a5-4480-2481-32ee-b2844a991c9d,1948-07-28,NaN,999-37-8036,S99939062,X79037907X,Mr.,Cody889,Hilll811,NaN,...,Stoneham Massachusetts US,568 Ryan Stravenue,Mashpee,Massachusetts,Barnstable County,NaN,41.577704,-70.507460,2.638801e+05,155042.0520
1162,cb1b2c74-d1c5-997c-6f8b-20ca9f332eef,1958-11-07,NaN,999-17-1411,S99963285,X2822177X,Mr.,Haywood675,Schroeder447,NaN,...,Peabody Massachusetts US,707 Heathcote Wall Suite 15,Marblehead,Massachusetts,Essex County,NaN,42.466700,-70.903323,1.548721e+06,217.1100

Because some of the patients are deceased we chose to remove them.

In [ ]:
patients = patients [patients ['DEATHDATE'].isna()]
patients

,Id,BIRTHDATE,DEATHDATE,SSN,DRIVERS,PASSPORT,PREFIX,FIRST,LAST,SUFFIX,...,BIRTHPLACE,ADDRESS,CITY,STATE,COUNTY,ZIP,LAT,LON,HEALTHCARE_EXPENSES,HEALTHCARE_COVERAGE
0,b9c610cd-28a6-4636-ccb6-c7a0d2a4cb85,2019-02-17,NaN,999-65-3251,NaN,NaN,NaN,Damon455,Langosh790,NaN,...,Middleborough Massachusetts US,620 Lynch Tunnel Apt 0,Springfield,Massachusetts,Hampden County,1104.0,42.080389,-72.480431,9.039165e+03,7964.1255
1,c1f1fcaa-82fd-d5b7-3544-c8f9708b06a8,2005-07-04,NaN,999-49-3323,S99941126,NaN,NaN,Thi53,Wunsch504,NaN,...,Danvers Massachusetts US,972 Tillman Branch Suite 48,Bellingham,Massachusetts,Norfolk County,NaN,42.035213,-71.482519,4.027234e+05,14064.1350
2,339144f8-50e1-633e-a013-f361391c4cff,1998-05-11,NaN,999-10-8743,S99996708,X75063318X,Mr.,Chi716,Greenfelder433,NaN,...,Athens Athens Prefecture GR,1060 Bernhard Crossroad Suite 15,Boston,Massachusetts,Suffolk County,2131.0,42.292557,-71.061160,5.719359e+05,787.5375
3,d488232e-bf14-4bed-08c0-a82f34b6a197,2003-01-28,NaN,999-56-6057,S99929424,NaN,Ms.,Phillis443,Walter473,NaN,...,Boston Massachusetts US,677 Ritchie Terrace,Hingham,Massachusetts,Plymouth County,2043.0,42.200491,-70.916076,5.825578e+05,104782.2070
4,217f95a3-4e10-bd5d-fb67-0cfb5e8ba075,1993-12-23,NaN,999-91-4320,S99991143,X44132498X,Mr.,Jerrold404,Herzog843,NaN,...,Boston Massachusetts US,276 Bernier Branch,Revere,Massachusetts,Suffolk County,NaN,42.381875,-70.999286,4.758269e+05,18067.0950
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1158,409330fa-7ffd-dbfb-4eba-2349d58a6324,1979-02-28,NaN,999-68-5445,S99991649,X72884711X,Mr.,Coy949,Schaden604,NaN,...,Fitchburg Massachusetts US,434 Hickle Throughway Suite 15,Amherst,Massachusetts,Hampshire County,NaN,42.380084,-72.527376,1.050937e+06,346.5075
1159,cb328021-a854-dc94-e7ae-426580477308,1964-05-31,NaN,999-10-6445,S99986790,X86596484X,Mrs.,Sherry479,Barrows492,NaN,...,Boston Massachusetts US,976 Ortiz Orchard,Stoughton,Massachusetts,Norfolk County,NaN,42.081223,-71.126028,8.031471e+05,553335.4420
1160,41862157-5c14-f706-4a94-d2929be969e7,1967-07-12,NaN,999-63-2407,S99976335,X68999803X,Mr.,Vance413,Jakubowski832,NaN,...,Brockton Massachusetts US,534 Strosin Corner,Gardner,Massachusetts,Worcester County,1440.0,42.604215,-72.013243,1.028321e+06,28607.5050
1161,d53c57a5-4480-2481-32ee-b2844a991c9d,1948-07-28,NaN,999-37-8036,S99939062,X79037907X,Mr.,Cody889,Hilll811,NaN,...,Stoneham Massachusetts US,568 Ryan Stravenue,Mashpee,Massachusetts,Barnstable County,NaN,41.577704,-70.507460,2.638801e+05,155042.0520
1162,cb1b2c74-d1c5-997c-6f8b-20ca9f332eef,1958-11-07,NaN,999-17-1411,S99963285,X2822177X,Mr.,Haywood675,Schroeder447,NaN,...,Peabody Massachusetts US,707 Heathcote Wall Suite 15,Marblehead,Massachusetts,Essex County,NaN,42.466700,-70.903323,1.548721e+06,217.1100

Adding a column with the patient's current age.

In [ ]:
# Converting birthdate to datetime
patients['BIRTHDATE'] = pd.to_datetime(patients['BIRTHDATE'], errors='coerce')

# Computing age (in years)
today = pd.Timestamp.today()
patients['AGE'] = (today - patients['BIRTHDATE']).dt.days / 365.25
patients['AGE'] = patients['AGE'].astype(int)

# Moving 'AGE' to the third column
cols = patients.columns.tolist()
cols.insert(2, cols.pop(cols.index('AGE')))
patients = patients[cols]

/tmp/ipython-input-2347968943.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  patients['BIRTHDATE'] = pd.to_datetime(patients['BIRTHDATE'], errors='coerce')
/tmp/ipython-input-2347968943.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  patients['AGE'] = (today - patients['BIRTHDATE']).dt.days / 365.25
/tmp/ipython-input-2347968943.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  patients['AGE'] = patients['AGE'].astype(int)

The we edit the Martial Status column to better fit natural language.

In [ ]:
patients.loc[patients['MARITAL'] == 'M', 'MARITAL'] = 'married'
patients.loc[patients['MARITAL'] == 'S', 'MARITAL'] = 'single'
patients['MARITAL'].fillna("unknown", inplace = True)
patients

/tmp/ipython-input-3686454553.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  patients['MARITAL'].fillna("unknown", inplace = True)
/tmp/ipython-input-3686454553.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  patients['MARITAL'].fillna("unknown", inplace = True)

,Id,BIRTHDATE,AGE,DEATHDATE,SSN,DRIVERS,PASSPORT,PREFIX,FIRST,LAST,...,BIRTHPLACE,ADDRESS,CITY,STATE,COUNTY,ZIP,LAT,LON,HEALTHCARE_EXPENSES,HEALTHCARE_COVERAGE
0,b9c610cd-28a6-4636-ccb6-c7a0d2a4cb85,2019-02-17,6,NaN,999-65-3251,NaN,NaN,NaN,Damon455,Langosh790,...,Middleborough Massachusetts US,620 Lynch Tunnel Apt 0,Springfield,Massachusetts,Hampden County,1104.0,42.080389,-72.480431,9.039165e+03,7964.1255
1,c1f1fcaa-82fd-d5b7-3544-c8f9708b06a8,2005-07-04,20,NaN,999-49-3323,S99941126,NaN,NaN,Thi53,Wunsch504,...,Danvers Massachusetts US,972 Tillman Branch Suite 48,Bellingham,Massachusetts,Norfolk County,NaN,42.035213,-71.482519,4.027234e+05,14064.1350
2,339144f8-50e1-633e-a013-f361391c4cff,1998-05-11,27,NaN,999-10-8743,S99996708,X75063318X,Mr.,Chi716,Greenfelder433,...,Athens Athens Prefecture GR,1060 Bernhard Crossroad Suite 15,Boston,Massachusetts,Suffolk County,2131.0,42.292557,-71.061160,5.719359e+05,787.5375
3,d488232e-bf14-4bed-08c0-a82f34b6a197,2003-01-28,22,NaN,999-56-6057,S99929424,NaN,Ms.,Phillis443,Walter473,...,Boston Massachusetts US,677 Ritchie Terrace,Hingham,Massachusetts,Plymouth County,2043.0,42.200491,-70.916076,5.825578e+05,104782.2070
4,217f95a3-4e10-bd5d-fb67-0cfb5e8ba075,1993-12-23,31,NaN,999-91-4320,S99991143,X44132498X,Mr.,Jerrold404,Herzog843,...,Boston Massachusetts US,276 Bernier Branch,Revere,Massachusetts,Suffolk County,NaN,42.381875,-70.999286,4.758269e+05,18067.0950
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1158,409330fa-7ffd-dbfb-4eba-2349d58a6324,1979-02-28,46,NaN,999-68-5445,S99991649,X72884711X,Mr.,Coy949,Schaden604,...,Fitchburg Massachusetts US,434 Hickle Throughway Suite 15,Amherst,Massachusetts,Hampshire County,NaN,42.380084,-72.527376,1.050937e+06,346.5075
1159,cb328021-a854-dc94-e7ae-426580477308,1964-05-31,61,NaN,999-10-6445,S99986790,X86596484X,Mrs.,Sherry479,Barrows492,...,Boston Massachusetts US,976 Ortiz Orchard,Stoughton,Massachusetts,Norfolk County,NaN,42.081223,-71.126028,8.031471e+05,553335.4420
1160,41862157-5c14-f706-4a94-d2929be969e7,1967-07-12,58,NaN,999-63-2407,S99976335,X68999803X,Mr.,Vance413,Jakubowski832,...,Brockton Massachusetts US,534 Strosin Corner,Gardner,Massachusetts,Worcester County,1440.0,42.604215,-72.013243,1.028321e+06,28607.5050
1161,d53c57a5-4480-2481-32ee-b2844a991c9d,1948-07-28,77,NaN,999-37-8036,S99939062,X79037907X,Mr.,Cody889,Hilll811,...,Stoneham Massachusetts US,568 Ryan Stravenue,Mashpee,Massachusetts,Barnstable County,NaN,41.577704,-70.507460,2.638801e+05,155042.0520
1162,cb1b2c74-d1c5-997c-6f8b-20ca9f332eef,1958-11-07,66,NaN,999-17-1411,S99963285,X2822177X,Mr.,Haywood675,Schroeder447,...,Peabody Massachusetts US,707 Heathcote Wall Suite 15,Marblehead,Massachusetts,Essex County,NaN,42.466700,-70.903323,1.548721e+06,217.1100

Finally, we drop some of the columns that contain excessive information.

In [ ]:
patients = patients.drop(columns=['BIRTHDATE','DEATHDATE','DRIVERS', 'PASSPORT', 'PREFIX', 'SUFFIX', 'MAIDEN','BIRTHPLACE', 'ETHNICITY', 'COUNTY', 'STATE', 'ZIP', 'LON', 'LAT','HEALTHCARE_EXPENSES', 'HEALTHCARE_COVERAGE' ])
patients

,Id,AGE,SSN,FIRST,LAST,MARITAL,RACE,GENDER,ADDRESS,CITY
0,b9c610cd-28a6-4636-ccb6-c7a0d2a4cb85,6,999-65-3251,Damon455,Langosh790,unknown,white,M,620 Lynch Tunnel Apt 0,Springfield
1,c1f1fcaa-82fd-d5b7-3544-c8f9708b06a8,20,999-49-3323,Thi53,Wunsch504,unknown,white,F,972 Tillman Branch Suite 48,Bellingham
2,339144f8-50e1-633e-a013-f361391c4cff,27,999-10-8743,Chi716,Greenfelder433,unknown,white,M,1060 Bernhard Crossroad Suite 15,Boston
3,d488232e-bf14-4bed-08c0-a82f34b6a197,22,999-56-6057,Phillis443,Walter473,unknown,white,F,677 Ritchie Terrace,Hingham
4,217f95a3-4e10-bd5d-fb67-0cfb5e8ba075,31,999-91-4320,Jerrold404,Herzog843,married,black,M,276 Bernier Branch,Revere
...,...,...,...,...,...,...,...,...,...,...
1158,409330fa-7ffd-dbfb-4eba-2349d58a6324,46,999-68-5445,Coy949,Schaden604,married,white,M,434 Hickle Throughway Suite 15,Amherst
1159,cb328021-a854-dc94-e7ae-426580477308,61,999-10-6445,Sherry479,Barrows492,married,white,F,976 Ortiz Orchard,Stoughton
1160,41862157-5c14-f706-4a94-d2929be969e7,58,999-63-2407,Vance413,Jakubowski832,married,asian,M,534 Strosin Corner,Gardner
1161,d53c57a5-4480-2481-32ee-b2844a991c9d,77,999-37-8036,Cody889,Hilll811,married,white,M,568 Ryan Stravenue,Mashpee
1162,cb1b2c74-d1c5-997c-6f8b-20ca9f332eef,66,999-17-1411,Haywood675,Schroeder447,married,asian,M,707 Heathcote Wall Suite 15,Marblehead

## Medical Records

The "medications.csv" contains information about the prescibed medication for some of the patients

In [ ]:
md = pd.read_csv("medications.csv")
md

,START,STOP,PATIENT,PAYER,ENCOUNTER,CODE,DESCRIPTION,BASE_COST,PAYER_COVERAGE,DISPENSES,TOTALCOST,REASONCODE,REASONDESCRIPTION
0,2020-02-17T10:40:32Z,NaN,b9c610cd-28a6-4636-ccb6-c7a0d2a4cb85,7c4411ce-02f1-39b5-b9ec-dfbea9ad3c1a,01efcc52-15d6-51e9-faa2-bee069fcbe44,1014676,cetirizine hydrochloride 5 MG Oral Tablet,21.45,0.0,21.0,450.45,NaN,NaN
1,2020-02-17T10:40:32Z,NaN,b9c610cd-28a6-4636-ccb6-c7a0d2a4cb85,7c4411ce-02f1-39b5-b9ec-dfbea9ad3c1a,01efcc52-15d6-51e9-faa2-bee069fcbe44,1870230,NDA020800 0.3 ML Epinephrine 1 MG/ML Auto-Inje...,231.58,0.0,21.0,4863.18,NaN,NaN
2,2013-06-24T06:39:19Z,2013-07-02T06:39:19Z,c1f1fcaa-82fd-d5b7-3544-c8f9708b06a8,42c4fca7-f8a9-3cd1-982a-dd9751bf3e2a,0b2794bd-ec2b-d34f-0610-2523b3b7fcf0,1043400,Acetaminophen 21.7 MG/ML / Dextromethorphan Hy...,7.59,0.0,1.0,7.59,10509002.0,Acute bronchitis (disorder)
3,2016-02-27T08:52:29Z,2016-03-14T08:52:29Z,c1f1fcaa-82fd-d5b7-3544-c8f9708b06a8,6e2f1a2d-27bd-3701-8d08-dae202c58632,a6d818dd-0983-fd1c-eefa-3d2295532c45,198405,Ibuprofen 100 MG Oral Tablet,12.48,0.0,1.0,12.48,NaN,NaN
4,2017-02-22T09:25:31Z,2017-06-02T09:25:31Z,c1f1fcaa-82fd-d5b7-3544-c8f9708b06a8,047f6ec3-6215-35eb-9608-f9dda363a44c,6474f606-5a1b-48c0-bbbf-ad6dcbc24d4e,313820,Acetaminophen 160 MG Chewable Tablet,4.77,0.0,3.0,14.31,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
8711,1994-05-10T20:45:19Z,1994-06-14T20:45:19Z,ef167059-cef0-12c4-49db-993ca3a20c01,b1c428d6-4f07-31e0-90f0-68ffa6ff8c76,d8ac68e9-37ee-d0ab-63df-846462811e7a,314076,lisinopril 10 MG Oral Tablet,0.02,0.0,35.0,0.70,59621000.0,Hypertension
8712,1994-06-14T20:45:19Z,1994-10-11T20:45:19Z,ef167059-cef0-12c4-49db-993ca3a20c01,b1c428d6-4f07-31e0-90f0-68ffa6ff8c76,6342fbfa-4931-5e45-5f8f-3bf2c470024c,106892,insulin human isophane 70 UNT/ML / Regular In...,249.91,0.0,3.0,749.73,44054006.0,Diabetes
8713,1994-06-14T20:45:19Z,1994-10-11T20:45:19Z,ef167059-cef0-12c4-49db-993ca3a20c01,b1c428d6-4f07-31e0-90f0-68ffa6ff8c76,6342fbfa-4931-5e45-5f8f-3bf2c470024c,310798,Hydrochlorothiazide 25 MG Oral Tablet,0.01,0.0,3.0,0.03,59621000.0,Hypertension
8714,1994-06-14T20:45:19Z,1994-10-11T20:45:19Z,ef167059-cef0-12c4-49db-993ca3a20c01,b1c428d6-4f07-31e0-90f0-68ffa6ff8c76,6342fbfa-4931-5e45-5f8f-3bf2c470024c,314076,lisinopril 10 MG Oral Tablet,0.02,0.0,119.0,2.38,59621000.0,Hypertension
8715,1994-10-11T20:45:19Z,1994-11-08T20:45:19Z,ef167059-cef0-12c4-49db-993ca3a20c01,b1c428d6-4f07-31e0-90f0-68ffa6ff8c76,26b0f6a1-a86c-c0e1-fbcb-3a39458da957,106892,insul,NaN,NaN,NaN,NaN,NaN,NaN

We keep only the columns that contain the patients' ids, their prescribed medication and their diagnosis that led to the prescription.

In [ ]:
md = md.loc[:, ['PATIENT', 'DESCRIPTION', 'REASONDESCRIPTION']]
md

,PATIENT,DESCRIPTION,REASONDESCRIPTION
0,b9c610cd-28a6-4636-ccb6-c7a0d2a4cb85,cetirizine hydrochloride 5 MG Oral Tablet,NaN
1,b9c610cd-28a6-4636-ccb6-c7a0d2a4cb85,NDA020800 0.3 ML Epinephrine 1 MG/ML Auto-Inje...,NaN
2,c1f1fcaa-82fd-d5b7-3544-c8f9708b06a8,Acetaminophen 21.7 MG/ML / Dextromethorphan Hy...,Acute bronchitis (disorder)
3,c1f1fcaa-82fd-d5b7-3544-c8f9708b06a8,Ibuprofen 100 MG Oral Tablet,NaN
4,c1f1fcaa-82fd-d5b7-3544-c8f9708b06a8,Acetaminophen 160 MG Chewable Tablet,NaN
...,...,...,...
8711,ef167059-cef0-12c4-49db-993ca3a20c01,lisinopril 10 MG Oral Tablet,Hypertension
8712,ef167059-cef0-12c4-49db-993ca3a20c01,insulin human isophane 70 UNT/ML / Regular In...,Diabetes
8713,ef167059-cef0-12c4-49db-993ca3a20c01,Hydrochlorothiazide 25 MG Oral Tablet,Hypertension
8714,ef167059-cef0-12c4-49db-993ca3a20c01,lisinopril 10 MG Oral Tablet,Hypertension
8715,ef167059-cef0-12c4-49db-993ca3a20c01,insul,NaN

We rename the columns for clarity.

In [ ]:
md=md.rename(columns = {"PATIENT":"Id","REASONDESCRIPTION":"DIAGNOSIS", "DESCRIPTION":"MEDICATION"})

Because a patient may have multiple perscriptions and diagnoses we group them in a signle row for each patients.

In [ ]:
m = md.groupby('Id').agg({'MEDICATION': lambda x: ', '.join(set(x)),'DIAGNOSIS': lambda x: ', '.join(set(x.dropna())) })
m

,MEDICATION,DIAGNOSIS
Id,,
0288c42c-43a1-9878-4a9d-6b96caa12c40,NITROFURANTOIN MACROCRYSTALS 50 MG Oral Capsu...,"Cystitis, Escherichia coli urinary tract infec..."
04f25f73-04b2-469c-3806-540417a0d61c,"Norinyl 1+50 28 Day Pack, piperacillin 2000 MG...","Acute bronchitis (disorder), Hypertension, Sep..."
05877654-69c4-d607-400e-e162ea103642,"Ibuprofen 400 MG Oral Tablet [Ibu], Acetaminop...","Acute bronchitis (disorder), Hypertension"
060e72d3-912e-55cd-0c92-5faa6cb7a6db,Amoxicillin 250 MG / Clavulanate 125 MG Oral T...,"Diabetes, Hypertension, Viral sinusitis (disor..."
0631ad5a-2c27-b7bf-f2eb-e2deec82692a,"Penicillin V Potassium 250 MG Oral Tablet, Ibu...",Streptococcal sore throat (disorder)
...,...,...
fc8e4748-86f4-1d49-af95-4c7e48678ca7,NDA020503 200 ACTUAT Albuterol 0.09 MG/ACTUAT ...,"Acute bronchitis (disorder), Childhood asthma,..."
fcca54e8-5abe-cd71-30a0-464f15368bea,"Etonogestrel 68 MG Drug Implant, Natazia 28 Da...",Viral sinusitis (disorder)
fee55adf-498c-5111-2136-e805906a3a74,"Hydrochlorothiazide 25 MG Oral Tablet, Acetami...","Acute bronchitis (disorder), Hypertension, Con..."
ff0e4d0e-6181-e36e-d817-64dbcaecb5d0,"Captopril 25 MG Oral Tablet, Nitroglycerin 0.4...",
ff9f14e4-d241-71fe-a501-2199e39aa79a,"atomoxetine 100 MG Oral Capsule, Ibuprofen 200...",Child attention deficit disorder

We merge the patients and mediactions tables

In [ ]:
patients=pd.merge(patients, m, on = "Id", how = "inner")
patients

,Id,AGE,SSN,FIRST,LAST,MARITAL,RACE,GENDER,ADDRESS,CITY,MEDICATION,DIAGNOSIS
0,b9c610cd-28a6-4636-ccb6-c7a0d2a4cb85,6,999-65-3251,Damon455,Langosh790,unknown,white,M,620 Lynch Tunnel Apt 0,Springfield,"cetirizine hydrochloride 5 MG Oral Tablet, NDA...",
1,c1f1fcaa-82fd-d5b7-3544-c8f9708b06a8,20,999-49-3323,Thi53,Wunsch504,unknown,white,F,972 Tillman Branch Suite 48,Bellingham,1 ML medroxyPROGESTERone acetate 150 MG/ML Inj...,Acute bronchitis (disorder)
2,339144f8-50e1-633e-a013-f361391c4cff,27,999-10-8743,Chi716,Greenfelder433,unknown,white,M,1060 Bernhard Crossroad Suite 15,Boston,"amLODIPine 2.5 MG Oral Tablet, lisinopril 10 M...",Hypertension
3,d488232e-bf14-4bed-08c0-a82f34b6a197,22,999-56-6057,Phillis443,Walter473,unknown,white,F,677 Ritchie Terrace,Hingham,"Acetaminophen 325 MG Oral Tablet, Amoxicillin ...","Acute bronchitis (disorder), Viral sinusitis (..."
4,217f95a3-4e10-bd5d-fb67-0cfb5e8ba075,31,999-91-4320,Jerrold404,Herzog843,married,black,M,276 Bernier Branch,Revere,Naproxen sodium 220 MG Oral Tablet,
...,...,...,...,...,...,...,...,...,...,...,...,...
225,ce54be47-1a8f-e1eb-9b4d-ca61378d9f41,100,999-47-6461,Trinh357,Sanford861,married,white,F,1023 Quigley Camp Unit 54,Danvers,"Hydrochlorothiazide 25 MG Oral Tablet, Acetami...","Hyperlipidemia, Viral sinusitis (disorder), Ac..."
226,730963e3-8472-75ab-fc64-5be33cdcc125,51,999-31-7174,Teresa94,Estévez304,married,white,F,821 Lehner Skyway,Bellingham,"Acetaminophen 325 MG Oral Tablet, Hydrochlorot...","Acute bronchitis (disorder), Hypertension"
227,4727c1ea-a23f-270d-f38f-e03857029aee,31,999-27-1176,Tristan353,Zulauf375,single,white,M,1049 Dare Branch Apt 3,Walpole,Ibuprofen 200 MG Oral Tablet,
228,be01726c-4937-554f-6d8f-58f8ec72ebab,27,999-36-8838,Wilford267,Hilpert278,unknown,asian,M,822 Casper Green,Beverly,"Naproxen sodium 220 MG Oral Tablet, Ibuprofen ...",
229,e92e2c9d-d257-4f3c-73aa-a6ee61ec8db1,43,999-11-8132,Pablo44,Schulist381,married,white,M,1043 McLaughlin Park,Dennis,"Allopurinol 100 MG Oral Tablet, Naproxen 500 M...","Acute bronchitis (disorder), Gout, Hypertension"

In [ ]:
#We convert the empty strings to NaN
import numpy as np
patients["DIAGNOSIS"] = patients["DIAGNOSIS"].replace("", np.nan)

##Allergies

The "allergies.csv" includes information about the patient's allergies

In [ ]:
allergies = pd.read_csv("allergies.csv")
allergies = allergies.loc[:, ['PATIENT', 'DESCRIPTION']]
allergies = allergies.rename(columns={'DESCRIPTION':'ALLERGY', 'PATIENT':'Id' })
allergies

                                       Id                     ALLERGY
0    b9c610cd-28a6-4636-ccb6-c7a0d2a4cb85           Latex (substance)
1    b9c610cd-28a6-4636-ccb6-c7a0d2a4cb85             Mold (organism)
2    b9c610cd-28a6-4636-ccb6-c7a0d2a4cb85  House dust mite (organism)
3    b9c610cd-28a6-4636-ccb6-c7a0d2a4cb85   Animal dander (substance)
4    b9c610cd-28a6-4636-ccb6-c7a0d2a4cb85    Grass pollen (substance)
..                                    ...                         ...
789  27cb1c2f-4ec0-6e24-d080-e46178f712d5        Tree nut (substance)
790  0cf08145-a634-329f-54d3-9cbd04ba18cc                     Aspirin
791  0cf08145-a634-329f-54d3-9cbd04ba18cc   Eggs (edible) (substance)
792  9c532b25-cd38-f13a-f2de-2f5538326ed6                     Aspirin
793  9c532b25-cd38-f13a-f2de-2f5538326ed6       Shellfish (substance)

[794 rows x 2 columns]

Because the values int the 'ALLERGY' column are in a ' value(descriptor)' format we chose to remove the descriptor.

In [ ]:
import re

allergies['ALLERGY'] = allergies['ALLERGY'].str.replace(r'\(.*?\)', '', regex=True)

Then we merge all the allergies for each patient in a single row

In [ ]:
allergies = allergies.groupby('Id').agg({'ALLERGY': lambda x: ', '.join(set(x))})
allergies

                                                                                ALLERGY
Id
0142b69f-57f0-9a08-4e2d-65a2b77fdea7  Shellfish , Aspirin, Animal dander , Sulfameth...
01d78eb5-7f50-45e9-f524-921196a3dffe  Mold , Tree pollen , Tree nut , Shellfish , Gr...
01f8bbfd-cfc6-3b97-8bc1-8da6f0b4a9a8  Mold , Tree pollen , Penicillin V, Grass polle...
0288c42c-43a1-9878-4a9d-6b96caa12c40                                        Cow's milk
02ceca12-357f-981e-dcf3-3d26d3c1ff82                                     Animal dander
...                                                                                 ...
fc8e4748-86f4-1d49-af95-4c7e48678ca7  Mold , Wheat , Animal dander , Eggs  , Soya be...
fca626fd-ab99-57fb-ba8d-f0bad053788b                                    Aspirin, Latex
fcca54e8-5abe-cd71-30a0-464f15368bea                                            Peanut
ff59238a-9508-b0e5-39f4-0d4afcbe6f43  Mold , Tree pollen , Grass pollen , Animal dan...
ff9337d4-4f6c-2182-c1aa-a0811a68a4ab  Mold , Grass pollen , Animal dander , House du...

[179 rows x 1 columns]

Once again we merge the allergies and patients data frames.

In [ ]:
patients = pd.merge(patients, allergies, on = "Id", how = "left")
patients

,Id,AGE,SSN,FIRST,LAST,MARITAL,RACE,GENDER,ADDRESS,CITY,MEDICATION,DIAGNOSIS,ALLERGY
0,b9c610cd-28a6-4636-ccb6-c7a0d2a4cb85,6,999-65-3251,Damon455,Langosh790,unknown,white,M,620 Lynch Tunnel Apt 0,Springfield,"cetirizine hydrochloride 5 MG Oral Tablet, NDA...",NaN,"Mold , Cow's milk , Aspirin, Shellfish , Grass..."
1,c1f1fcaa-82fd-d5b7-3544-c8f9708b06a8,20,999-49-3323,Thi53,Wunsch504,unknown,white,F,972 Tillman Branch Suite 48,Bellingham,1 ML medroxyPROGESTERone acetate 150 MG/ML Inj...,Acute bronchitis (disorder),NaN
2,339144f8-50e1-633e-a013-f361391c4cff,27,999-10-8743,Chi716,Greenfelder433,unknown,white,M,1060 Bernhard Crossroad Suite 15,Boston,"amLODIPine 2.5 MG Oral Tablet, lisinopril 10 M...",Hypertension,NaN
3,d488232e-bf14-4bed-08c0-a82f34b6a197,22,999-56-6057,Phillis443,Walter473,unknown,white,F,677 Ritchie Terrace,Hingham,"Acetaminophen 325 MG Oral Tablet, Amoxicillin ...","Acute bronchitis (disorder), Viral sinusitis (...",NaN
4,217f95a3-4e10-bd5d-fb67-0cfb5e8ba075,31,999-91-4320,Jerrold404,Herzog843,married,black,M,276 Bernier Branch,Revere,Naproxen sodium 220 MG Oral Tablet,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
225,ce54be47-1a8f-e1eb-9b4d-ca61378d9f41,100,999-47-6461,Trinh357,Sanford861,married,white,F,1023 Quigley Camp Unit 54,Danvers,"Hydrochlorothiazide 25 MG Oral Tablet, Acetami...","Hyperlipidemia, Viral sinusitis (disorder), Ac...","Penicillin V, Peanut"
226,730963e3-8472-75ab-fc64-5be33cdcc125,51,999-31-7174,Teresa94,Estévez304,married,white,F,821 Lehner Skyway,Bellingham,"Acetaminophen 325 MG Oral Tablet, Hydrochlorot...","Acute bronchitis (disorder), Hypertension",NaN
227,4727c1ea-a23f-270d-f38f-e03857029aee,31,999-27-1176,Tristan353,Zulauf375,single,white,M,1049 Dare Branch Apt 3,Walpole,Ibuprofen 200 MG Oral Tablet,NaN,NaN
228,be01726c-4937-554f-6d8f-58f8ec72ebab,27,999-36-8838,Wilford267,Hilpert278,unknown,asian,M,822 Casper Green,Beverly,"Naproxen sodium 220 MG Oral Tablet, Ibuprofen ...",NaN,NaN
229,e92e2c9d-d257-4f3c-73aa-a6ee61ec8db1,43,999-11-8132,Pablo44,Schulist381,married,white,M,1043 McLaughlin Park,Dennis,"Allopurinol 100 MG Oral Tablet, Naproxen 500 M...","Acute bronchitis (disorder), Gout, Hypertension",NaN

In [ ]:
patients = patients.iloc[0:300]
patients

,Id,AGE,SSN,FIRST,LAST,MARITAL,RACE,GENDER,ADDRESS,CITY,MEDICATION,DIAGNOSIS,ALLERGY
0,b9c610cd-28a6-4636-ccb6-c7a0d2a4cb85,6,999-65-3251,Damon455,Langosh790,unknown,white,M,620 Lynch Tunnel Apt 0,Springfield,"cetirizine hydrochloride 5 MG Oral Tablet, NDA...",NaN,"Mold , Cow's milk , Aspirin, Shellfish , Grass..."
1,c1f1fcaa-82fd-d5b7-3544-c8f9708b06a8,20,999-49-3323,Thi53,Wunsch504,unknown,white,F,972 Tillman Branch Suite 48,Bellingham,1 ML medroxyPROGESTERone acetate 150 MG/ML Inj...,Acute bronchitis (disorder),NaN
2,339144f8-50e1-633e-a013-f361391c4cff,27,999-10-8743,Chi716,Greenfelder433,unknown,white,M,1060 Bernhard Crossroad Suite 15,Boston,"amLODIPine 2.5 MG Oral Tablet, lisinopril 10 M...",Hypertension,NaN
3,d488232e-bf14-4bed-08c0-a82f34b6a197,22,999-56-6057,Phillis443,Walter473,unknown,white,F,677 Ritchie Terrace,Hingham,"Acetaminophen 325 MG Oral Tablet, Amoxicillin ...","Acute bronchitis (disorder), Viral sinusitis (...",NaN
4,217f95a3-4e10-bd5d-fb67-0cfb5e8ba075,31,999-91-4320,Jerrold404,Herzog843,married,black,M,276 Bernier Branch,Revere,Naproxen sodium 220 MG Oral Tablet,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
225,ce54be47-1a8f-e1eb-9b4d-ca61378d9f41,100,999-47-6461,Trinh357,Sanford861,married,white,F,1023 Quigley Camp Unit 54,Danvers,"Hydrochlorothiazide 25 MG Oral Tablet, Acetami...","Hyperlipidemia, Viral sinusitis (disorder), Ac...","Penicillin V, Peanut"
226,730963e3-8472-75ab-fc64-5be33cdcc125,51,999-31-7174,Teresa94,Estévez304,married,white,F,821 Lehner Skyway,Bellingham,"Acetaminophen 325 MG Oral Tablet, Hydrochlorot...","Acute bronchitis (disorder), Hypertension",NaN
227,4727c1ea-a23f-270d-f38f-e03857029aee,31,999-27-1176,Tristan353,Zulauf375,single,white,M,1049 Dare Branch Apt 3,Walpole,Ibuprofen 200 MG Oral Tablet,NaN,NaN
228,be01726c-4937-554f-6d8f-58f8ec72ebab,27,999-36-8838,Wilford267,Hilpert278,unknown,asian,M,822 Casper Green,Beverly,"Naproxen sodium 220 MG Oral Tablet, Ibuprofen ...",NaN,NaN
229,e92e2c9d-d257-4f3c-73aa-a6ee61ec8db1,43,999-11-8132,Pablo44,Schulist381,married,white,M,1043 McLaughlin Park,Dennis,"Allopurinol 100 MG Oral Tablet, Naproxen 500 M...","Acute bronchitis (disorder), Gout, Hypertension",NaN

In [ ]:
patients.to_csv('medical_records.csv')

## Conversion to Natural Language

In order to train our csv we must convert our dataframe to natural langauge and export the output in '.docx' format.

In [ ]:
#finding out which columns contain NaN values

patients.isna().sum()

In [ ]:

#The following function returns an empty string if a value is NaN/None/NA.
#Otherwise, it converts the value to a string.
def str_convert(value):

    if pd.isna(value):
        return ""
    return str(value)

#The following funtion converts each row of our patients dataframe to a json object
def row_to_json(row):
    Id = str_convert(row["Id"])
    FIRST = str_convert(row["FIRST"])
    LAST = str_convert(row["LAST"])
    SSN = str_convert(row["SSN"])
    AGE = str_convert(row["AGE"])
    GENDER = str_convert(row["GENDER"])
    MARITAL = str_convert(row["MARITAL"])
    RACE = str_convert(row["RACE"])
    ADDRESS = str_convert(row["ADDRESS"])
    CITY = str_convert(row["CITY"])
    DIAGNOSIS = str_convert(row["DIAGNOSIS"])
    MEDICATION = str_convert(row["MEDICATION"])
    ALLERGY = str_convert(row["ALLERGY"])

    TEXT = (
        f"The patient with id {Id} is named {FIRST} {LAST}. "
        f"Their social security number (SSN) is {SSN}. "
        f"Their age is {AGE} years old, and their gender is listed as {GENDER}. "
        f"The patient's current marital status is {MARITAL}. "
        f"Their race is {RACE} ."
        f"Their home address is {ADDRESS} located in the city of {CITY}. "
    )

    if DIAGNOSIS:
      TEXT += f"As of today, the patient has been diagnosed with: {DIAGNOSIS}. "

    TEXT += f"The medication they have been prescribed includes: {MEDICATION}. "

    if ALLERGY:
         TEXT  += f"Their known allergies are: {ALLERGY}."

    patient_record = {
        "id": Id,
        "name": FIRST,
        "surname": LAST,
        "ssn": SSN,
        "age": AGE,
        "gender": GENDER,
        "marital_status": MARITAL,
        "race": RACE,
        "address": ADDRESS,
        "city": CITY,
        "diagnosis": DIAGNOSIS,
        "medications": MEDICATION,
        "allergies": ALLERGY,
        "text": TEXT

    }

    return patient_record

import json
#each patient record is stored in a .json file
with open("patients.jsonl", "w", encoding="utf-8") as f:
    for _, row in patients.iterrows():
        json.dump(row_to_json(row), f)
        f.write("\n")

Thden we export our natural language text in '.docx' format.

In [ ]:
#!pip install python-docx

In [ ]:
#from docx import Document

# Create a new Word document
#doc = Document()

#doc.add_heading("The following is a list of the patients in UNIPI Medical Clinic:\n")

#Adding each patient's paragraph
#for paragraph in nl:
 # doc.add_paragraph(paragraph + "\n")

# Save the document
#doc.save("patients.docx")